ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DISPATCHER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TECHNICIAN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VIEWER';
