#!/usr/bin/env bash

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${MYTITAN_EVIDENCE_DIR:-${REPO_ROOT}/evidence}/screenshots"
MANIFEST="${OUT_DIR}/manifest.json"
MD="${OUT_DIR}/manifest.md"

mkdir -p "${OUT_DIR}"

routes=(
  "marketing-homepage|marketing|/|desktop,mobile|light"
  "marketing-pricing|marketing|/pricing|desktop,mobile|light"
  "signup|app|/signup|desktop,mobile|light"
  "login|app|/login|desktop,mobile|light"
  "dashboard-shell|app|/dashboard|desktop,mobile|light,dark"
  "bookings|app|/dashboard/bookings|desktop,mobile|light"
  "calendar|app|/dashboard/calendar|desktop,mobile|light"
  "jobs|app|/dashboard/jobs|desktop,mobile|light"
  "job-sheet|app|/dashboard/jobs/e2e-job-active|desktop,mobile|light"
  "invoices-payments|app|/dashboard/finance|desktop,mobile|light"
  "communications|app|/dashboard/communications|desktop,mobile|light"
  "settings|app|/dashboard/settings|desktop,mobile|light"
  "public-booking|app|/portal/booking/e2e-public-booking|desktop,mobile|light"
  "trade-portal|app|/trade/portal/e2e-trade-token|desktop,mobile|light"
  "platform-admin|app|/platform|desktop,mobile|light"
  "tenant-360|app|/platform/tenants/e2e-company|desktop,mobile|light"
)

{
  echo '{'
  echo '  "generatedAt": "'"$(date -Is)"'",'
  echo '  "status": "needs_evidence",'
  echo '  "privacy": "Seeded E2E state only. No secrets, raw tenant data exports, payment secrets, private keys, or .env content are allowed in screenshots.",'
  echo '  "updateCommand": "bash ./scripts/collect-screenshot-baseline.sh after Playwright screenshot capture specs are run",'
  echo '  "routes": ['
  first=1
  for row in "${routes[@]}"; do
    IFS='|' read -r key app route viewports themes <<EOF
${row}
EOF
    [ "${first}" -eq 1 ] || echo ','
    first=0
    printf '    {"key":"%s","app":"%s","route":"%s","viewports":"%s","themes":"%s","status":"slot_created","artifactPath":"evidence/screenshots/%s"}' "${key}" "${app}" "${route}" "${viewports}" "${themes}" "${key}"
  done
  echo
  echo '  ]'
  echo '}'
} >"${MANIFEST}"

cat >"${MD}" <<EOF
# Screenshot Regression Manifest

- Generated: $(date -Is)
- Status: needs_evidence
- Seed source: deterministic E2E fixtures
- Privacy: no secrets, no .env, no raw customer payment secrets, and no tenant leakage.

This manifest creates the required route baseline slots. Stored image baselines must be generated by the Playwright screenshot command before visual regression can be treated as proven.
EOF

echo "SCREENSHOT_MANIFEST:${MANIFEST}"
