#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_SRC="${ROOT_DIR}/api/src"
APP_PAGES="${ROOT_DIR}/app/pages"
OUT_FILE="${ROOT_DIR}/docs/audit/routes-inventory.md"

mkdir -p "$(dirname "$OUT_FILE")"

GEN_TS_UTC="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
GEN_CMD="scripts/generate-routes-inventory.sh"

python3 - "$API_SRC" "$APP_PAGES" "$OUT_FILE" "$GEN_TS_UTC" "$GEN_CMD" <<'PY2'
import re
import sys
from pathlib import Path

api_src = Path(sys.argv[1])
app_pages = Path(sys.argv[2])
out_file = Path(sys.argv[3])
gen_ts = sys.argv[4]
gen_cmd = sys.argv[5]

METHOD_RE = re.compile(r"@(Get|Post|Put|Patch|Delete)\(([^\)]*)\)")
CONTROLLER_RE = re.compile(r"@Controller\(([^\)]*)\)")


def clean_decorator_arg(raw: str) -> str:
    s = raw.strip()
    if not s:
        return ""
    if s in ('""', "''"):
        return ""
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('\"', "'", "`"):
        return s[1:-1]
    return s


def render_route(base: str, frag: str) -> str:
    b = base.strip().strip("/") if base else ""
    f = frag.strip().strip("/") if frag else ""
    parts = [p for p in (b, f) if p]
    if not parts:
        return "/"
    return "/" + "/".join(parts)


def discover_api_routes():
    rows = []
    for fp in sorted(api_src.rglob("*.controller.ts")):
        rel = fp.relative_to(api_src).as_posix()
        current_base = ""
        with fp.open("r", encoding="utf-8") as f:
            for ln, line in enumerate(f, start=1):
                cm = CONTROLLER_RE.search(line)
                if cm:
                    current_base = clean_decorator_arg(cm.group(1))
                mm = METHOD_RE.search(line)
                if mm:
                    method = mm.group(1).upper()
                    fragment = clean_decorator_arg(mm.group(2))
                    path = render_route(current_base, fragment)
                    controller_name = fp.stem.replace(".controller", "")
                    rows.append((method, path, controller_name, f"{rel}:{ln}"))
    rows.sort(key=lambda r: (r[1], r[0], r[3]))
    return rows


def map_page_to_route(rel_path: str) -> str:
    route = rel_path
    if route.endswith(".tsx"):
        route = route[:-4]
    elif route.endswith(".ts"):
        route = route[:-3]

    if route.endswith("/index"):
        route = route[:-6]
    elif route == "index":
        route = ""

    route = re.sub(r"\[\.\.\.([^\]]+)\]", r":...\1", route)
    route = re.sub(r"\[([^\]]+)\]", r":\1", route)

    return "/" + route if route else "/"


def discover_app_pages():
    rows = []
    for fp in sorted([p for p in app_pages.rglob("*") if p.is_file() and p.suffix in (".tsx", ".ts")]):
        rel = fp.relative_to(app_pages).as_posix()
        if rel.startswith("api/"):
            continue
        rows.append((map_page_to_route(rel), rel))
    rows.sort(key=lambda r: (r[0], r[1]))
    return rows


api_rows = discover_api_routes()
app_rows = discover_app_pages()

lines = []
lines.append("# Routes Inventory")
lines.append("")
lines.append(f"- Generated UTC: `{gen_ts}`")
lines.append(f"- Generated by: `{gen_cmd}`")
lines.append("")
lines.append("This file is generated for drift detection. Re-run the generator script instead of manual edits.")
lines.append("")
lines.append("## API Routes (NestJS)")
lines.append("")
lines.append("Limitations: best-effort static decorator parsing. Dynamic/computed decorator args may be represented literally or missed.")
lines.append("")
lines.append("| Method | Path | Controller | File |")
lines.append("|---|---|---|---|")
for method, path, controller, file_ref in api_rows:
    lines.append(f"| `{method}` | `{path}` | `{controller}` | `{file_ref}` |")

lines.append("")
lines.append("## App Pages (Next.js Pages Router)")
lines.append("")
lines.append("Notes: routes are derived from `app/pages`; dynamic segments are shown as `:param`.")
lines.append("")
lines.append("| Route | File |")
lines.append("|---|---|")
for route, file_ref in app_rows:
    lines.append(f"| `{route}` | `{file_ref}` |")

out_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY2

echo "Wrote ${OUT_FILE}"
