#!/usr/bin/env bash

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${MYTITAN_ARCHITECTURE_DOCS_DIR:-${REPO_ROOT}/docs/architecture/generated}"
MANIFEST="${OUT_DIR}/manifest.md"

mkdir -p "${OUT_DIR}"

route_count="$(find "${REPO_ROOT}/app/pages" "${REPO_ROOT}/marketing/pages" -type f \( -name '*.tsx' -o -name '*.ts' \) 2>/dev/null | wc -l | tr -d ' ')"
controller_count="$(find "${REPO_ROOT}/api/src" -name '*.controller.ts' 2>/dev/null | wc -l | tr -d ' ')"
module_count="$(find "${REPO_ROOT}/api/src" -name '*.module.ts' 2>/dev/null | wc -l | tr -d ' ')"
model_count="$(rg -n '^model ' "${REPO_ROOT}/api/prisma/schema.prisma" 2>/dev/null | wc -l | tr -d ' ')"
provider_hits="$(rg -n 'Stripe|GoCardless|SumUp|Zettle|Worldpay|Square|PayPal|Revolut|Adyen|Mollie|Klarna|Xero|QuickBooks|Sage|WhatsApp|Twilio|OpenAI' "${REPO_ROOT}/api/src" "${REPO_ROOT}/docs" 2>/dev/null | wc -l | tr -d ' ')"

cat >"${OUT_DIR}/route-inventory.md" <<EOF
# Route Inventory

- Generated by: scripts/generate-architecture-docs.sh
- App and marketing page files: ${route_count}
- Source roots: app/pages, marketing/pages
EOF

cat >"${OUT_DIR}/api-module-inventory.md" <<EOF
# API Module Inventory

- Generated by: scripts/generate-architecture-docs.sh
- Nest controller files: ${controller_count}
- Nest module files: ${module_count}
- Source root: api/src
EOF

cat >"${OUT_DIR}/prisma-model-inventory.md" <<EOF
# Prisma Model Inventory

- Generated by: scripts/generate-architecture-docs.sh
- Prisma models: ${model_count}
- Source: api/prisma/schema.prisma
EOF

cat >"${OUT_DIR}/integration-provider-inventory.md" <<EOF
# Integration Provider Inventory

- Generated by: scripts/generate-architecture-docs.sh
- Provider references found: ${provider_hits}
- Provider readiness remains evidence-gated. No live provider readiness is claimed from code references alone.
EOF

cat >"${OUT_DIR}/payment-tenant-boundaries.md" <<EOF
# Payment And Tenant Boundaries

MyTitan platform billing and tenant customer payment providers remain separate. MyTitan billing Stripe must not route customer money, mutate customer payment provider products, or imply provider readiness without tenant-owned credentials and canary evidence.

Tenant/platform boundaries are enforced through platform-admin routes, support-mode audit, RBAC, tenant-scoped API checks, and stable isolation tests.
EOF

cat >"${OUT_DIR}/release-pipeline-topology.md" <<EOF
# Release Pipeline And Deployment Topology

- Stable suite: scripts/validate-e2e-stable.sh
- Health: scripts/healthcheck.sh
- Readiness: scripts/production-readiness-check.sh
- Release evidence package: scripts/create-release-evidence-package.sh
- Deployment topology: Docker Compose services app, api, marketing, postgres, redis, and supporting local release services as declared in docker-compose.yml.
- Data retention/archive approach: tenant-scoped archive and retention controls are documented in existing architecture and launch-operation evidence.
EOF

cat >"${MANIFEST}" <<EOF
# Generated Architecture Manifest

- Generated by: scripts/generate-architecture-docs.sh
- Route inventory: docs/architecture/generated/route-inventory.md
- API module inventory: docs/architecture/generated/api-module-inventory.md
- Prisma model inventory: docs/architecture/generated/prisma-model-inventory.md
- Integration/provider inventory: docs/architecture/generated/integration-provider-inventory.md
- Payment architecture and tenant/platform boundaries: docs/architecture/generated/payment-tenant-boundaries.md
- Event/webhook flow, release pipeline, deployment topology, data retention/archive approach: docs/architecture/generated/release-pipeline-topology.md

These files are generated from repository structure and existing architecture constraints. They do not expose secrets and do not claim external certifications or production provider readiness.
EOF

echo "ARCHITECTURE_MANIFEST:${MANIFEST}"
