ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'DAMAGE_PHOTO';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'TORQUE_EVIDENCE';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'PAYMENT_EVIDENCE';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'SUPPLIER_DOC';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'COMPLIANCE_DOC';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'VIDEO';
