ALTER TYPE "TenantIntegrationProvider" ADD VALUE IF NOT EXISTS 'XERO';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'ESTIMATE';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'PAYMENT';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'COMPLIANCE';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'BEFORE_PHOTO';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'AFTER_PHOTO';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'EVIDENCE';
ALTER TYPE "DocumentArtifactKind" ADD VALUE IF NOT EXISTS 'EXPORT';
